### ISSUE TITLE
Kanban setup

### ISSUE THREAD

**Issue by Nuga0909** [yuvenalmash/API-based-webapp#3]
https://github.com/yuvenalmash/API-based-webapp

- We have 2 people in the group.

**Comment by TuyishimireEric** [comment]
# Status: REQUIRED CHANGES :recycle: 
### Hi  @Team    👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Highlights 
✔️  Your Cards are assigned to team members. 👍 

## Required Changes ♻️
- [ ] **You have done a great job creating cards** 👍👍 However, It would be better to use a copy of [this template board](https://github.com/microverseinc/curriculum-javascript/projects/1).

* As your team has **two** people, Kindly remember to remove all cards with the `Student C` suffix on the template from students' copies of the template. **Number of cards on board should be equal to 15**🙏 

- [ ] **Once you are done:**

 * You will decide who is `Student A`, and `Student B`. So each card with `Student A` in its title should always be assigned to the same student (and analogical for other students).
 * All cards with `group task` in the title should be assigned to someone (it does not matter to whom as students had freedom with that).

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
Hi @Nuga0909 and @yuvenalmash,

## Highlights!
- Descriptive pull request ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
